personilDitugaskan:
  label: 'Personil Ditugaskan'
  view: 
    list: $/yfktn/berikanarahan/models/personilditugaskan/columns.yaml
    toolbarButtons: create|delete
  customMessages:
    buttonCreate: 'Tambahkan Personil Ditugaskan'
    buttonDelete: 'Hapus Personil'
  manage: 
    form: $/yfktn/berikanarahan/models/personilditugaskan/fields.yaml
    list: $/yfktn/berikanarahan/models/personilditugaskan/columns.yaml
progressPenanganan:
  label: 'Progress Penanganan'
  emptyMessage: 'Belum ada progress ...'
  view: 
    list: $/yfktn/berikanarahan/models/pesan/columns.yaml
    toolbarButtons: create|delete
  customMessages: 
    buttonCreate: 'Catatkan Progress'
    buttonDelete: 'Hapus Progress'
  manage: 
    title: 'Catatkan Progress'
    form: $/yfktn/berikanarahan/models/pesan/fields.yaml
    list: $/yfktn/berikanarahan/models/pesan/columns.yaml
narahubung:
  label: 'Narahubung'
  emptyMessage: 'Belum ada narahubung dimasukkan, atau arahan ini tidak membutuhkannya.'
  view: 
    list: $/yfktn/berikanarahan/models/narahubung/columns.yaml
    toolbarButtons: create|delete
  customMessages:
    buttonCreate: 'Tambahkan Narahubung'
    buttonDelete: 'Hapus Narahubung'
  manage: 
    title: 'Tambahkan Narahubung'
    form: $/yfktn/berikanarahan/models/narahubung/fields.yaml
    list: $/yfktn/berikanarahan/models/narahubung/columns.yaml
