personilDitugaskan:
  label: 'Personil Ditugaskan'
  view: 
    list: $/yfktn/berikanarahan/models/personilditugaskan/columns.yaml
    toolbarButtons: create|delete
  manage: 
    form: $/yfktn/berikanarahan/models/personilditugaskan/fields.yaml
    list: $/yfktn/berikanarahan/models/personilditugaskan/columns.yaml
